CREATE TABLE IF NOT EXISTS brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS model(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(255) NOT NULL,
    brand_id bigint NOT NULL,
    FOREIGN KEY (brand_id) REFERENCES brand (id)
);

CREATE TABLE IF NOT EXISTS vehicle_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS sub_type(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_type_name VARCHAR(255) NOT NULL,
    vehicle_type_id bigint NOT NULL,
    FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_type (id)
);

CREATE TABLE IF NOT EXISTS address(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zip_code VARCHAR(10),
    country VARCHAR(100) NOT NULL,
    region VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    district VARCHAR(255),
    street VARCHAR(255) NOT NULL,
    house bigint NOT NULL,
    apartment VARCHAR(50) NOT NULL,
    additional_info VARCHAR(255),
    create_date timestamp
);

CREATE TABLE IF NOT EXISTS branch(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(255),
    address_id bigint NOT NULL,
    working_time VARCHAR(255),
    phone VARCHAR(50),
    FOREIGN KEY (address_id) REFERENCES address (id)
);